name: conlen
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - patsy
  - pip
  - pymvpa2
  - python=2.7
  - pyyaml
  - r=3.6.0
  - scikit-learn
  - scipy
  - statsmodels
  - yaml
  - pip:
    - nilearn==0.5.2
